// <auto-generated />
namespace GameMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddSignatureName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSignatureName));
        
        string IMigrationMetadata.Id
        {
            get { return "201710172252306_AddSignatureName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
